dependencies:
- name: mariadb
  version: 7.x.x
  repository: file://.charts/mariadb/
  condition: mariadb.enabled
- name: postgresql
  version: 7.x.x
  repository: file://.charts/postgresql/
  condition: postgresql.enabled
