configmap:
  server:
    addr: 
    - 0.0.0.0:53
    http_cmd_addr: 0.0.0.0:9000
    handler_count: 512 
    enable_tcp: false
  enable_modules:
  - query_log
  - view
  - cache
  - forwarder
  - recursor
  - local_data
  logger:
    query_log: 
      enable: true
      qlog_extension: true
    general_log:
      enable: false
  cache: 
    enable: true
    short_answer: true
    prefetch: false
  forwarder:
    forward_zone_for_view:
    - view: "default"
      zones:
      - name: "cn"
        forward_style: "rtt"
        forwarders:
        - 114.114.114.114:53
  local_data:
  - view: default
    redirect:
    - www.zdns.cn 3600 A 107.150.125.17
  recursor:
  - view: default
    enable: true
  resolver:
    check_cname_indirect: false

deployment:
  replicas: 1
  image:
    repository: zdnscloud/vanguard
    tag: v0.2
    pullPolicy: IfNotPresent
  annotations:
    prometheus:
      port: 9000
  resources:
    requests:
      cpu: 10m
      memory: 50Mi

service:
  port: 53
  protocol: UDP
