{{- $ca := genCA "harbor-ca" 7300 }}
{{- $cert := genSignedCert .Values.ingress.core nil (list .Values.ingress.core .Values.ingress.notary) 7300 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.ingress" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  {{- if eq .Values.ingress.caCrt ""}}
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  {{- else}}
  tls.crt: {{ .Values.ingress.tlsCrt | b64enc | quote }}
  tls.key: {{ .Values.ingress.tlsKey | b64enc | quote }}
  ca.crt: {{ .Values.ingress.caCrt | b64enc | quote }}
  {{- end}}