apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name}}-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size}}Gi
  storageClassName: {{ .Values.persistence.storageClass}}