backend:
  es:
    host: elasticsearch-master
    port: 9200
  forward:
    host: fluentd
    port: 24284
  http:
    format: msgpack
    host: 127.0.0.1
    port: 80
    uri: /
  type: es
env: []
existingConfigMap: ""
extraVolumeMounts: []
extraVolumes: []
filter: {}
image:
  fluent_bit:
    repository: fluent/fluent-bit
    tag: 0.12.11
  pullPolicy: Always
nodeSelector: {}
on_minikube: false
rbac:
  create: true
  serviceAccountName: default
resources:
  limits:
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi
tolerations: []
