apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: zcloud:{{ .Release.Namespace }}-{{ template "vanguard.fullname" . }}
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    app: {{ template "vanguard.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    kubernetes.io/bootstrapping: rbac-defaults
subjects:
  - kind: ServiceAccount
    name: {{ template "vanguard.serviceAccount.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zcloud:{{ .Release.Namespace }}-{{ template "vanguard.fullname" . }}
