apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "vanguard.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "vanguard.fullname" . }}
data:
  vanguard.conf: |
{{ toYaml .Values.configmap | default "{}" | indent 4 }}
