apiVersion: v1
kind: Service
metadata:
  name: {{ template "zeppelin-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.zeppelin.component }}"
spec:
  ports:
    - name: http
      port: {{ .Values.zeppelin.servicePort }}
      targetPort: {{ .Values.zeppelin.containerPort }}
  selector:
    component: "{{ .Release.Name }}-{{ .Values.zeppelin.component }}"
  type: {{ .Values.zeppelin.serviceType }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "zeppelin-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.zeppelin.component }}"
spec:
  replicas: {{ default 1 .Values.zeppelin.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{ .Release.Name }}-{{ .Values.zeppelin.component }}"
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        component: "{{ .Release.Name }}-{{ .Values.zeppelin.component }}"
    spec:
      containers:
        - name: {{ template "zeppelin-fullname" . }}
          image: "{{ .Values.zeppelin.image }}:{{ .Values.zeppelin.imageTag }}"
          ports:
            - containerPort: {{ .Values.zeppelin.containerPort }}
              name: http
          resources:
            requests:
              cpu: "{{ .Values.zeppelin.cpu }}"
          env:
            - name: SPARK_MASTER
              value: "spark://{{ template "master-fullname" . }}:{{ .Values.master.servicePort }}"
          volumeMounts:
          {{- if .Values.zeppelin.persistence.config.enabled }}
            - name: {{ template "master-fullname" . }}-config
              mountPath: /zeppelin/conf
          {{- end }}
          {{- if .Values.zeppelin.persistence.notebook.enabled }}
            - name: {{ template "master-fullname" . }}-notebook
              mountPath: /zeppelin/notebook
          {{- end }}
      volumes:
        {{- if .Values.zeppelin.persistence.config.enabled }}
        - name: {{ template "master-fullname" . }}-config
          persistentVolumeClaim:
            claimName: {{ template "zeppelin-fullname" . }}-config
        {{- end }}
        {{- if .Values.zeppelin.persistence.notebook.enabled }}
        - name: {{ template "master-fullname" . }}-notebook
          persistentVolumeClaim:
            claimName: {{ template "zeppelin-fullname" . }}-notebook
        {{- end }}
