apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-sql-test-{{ randAlphaNum 5 | lower }}"
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: {{ .Release.Name }}-sql-test
      image: {{ .Values.master.image }}:{{ .Values.master.imageTag }}
      command: ["{{ .Values.spark.path }}/bin/spark-sql", "--master",
                "spark://{{ .Release.Name }}-master:{{ .Values.master.servicePort }}", "-e",
                "show databases;"]
  restartPolicy: Never
