{{- $ingress := .Values.zeppelin.ingress -}}
{{- $fullName := include "zeppelin-fullname" . -}}
{{- if $ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "zeppelin-fullname" . }}
{{- if $ingress.annotations }}
  annotations:
{{ toYaml $ingress.annotations | indent 4 }}
{{- end }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.zeppelin.component }}"
spec:
{{- if $ingress.tls }}
  tls:
  {{- range $ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
    secretName: {{ .secretName | default (printf "%s-tls" $fullName) }}
{{- end }}
{{- end }}
  {{- if $ingress.hosts }}
  rules:
  {{- range $ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: {{ $ingress.path }}
        backend:
          serviceName: {{ $fullName }}
          servicePort: http
  {{- end }}
{{- else }}
  backend:
    serviceName: {{ template "zeppelin-fullname" . }}
    servicePort: http
{{- end }}
{{- end }}
