apiVersion: v1
appVersion: v0.5.0
description: A Helm chart for k8s prometheus adapter
home: https://github.com/DirectXMan12/k8s-prometheus-adapter
keywords:
- hpa
- metrics
- prometheus
- adapter
maintainers:
- email: mattias.gees@jetstack.io
  name: mattiasgees
- name: steven-sheehy
- email: hfernandez@mesosphere.com
  name: hectorj2f
name: prometheus-adapter
sources:
- https://github.com/kubernetes/charts
- https://github.com/DirectXMan12/k8s-prometheus-adapter
version: 1.4.0
