apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    zcloud.cn/update-on-config-change: "true"
  labels:
    app: {{ template "vanguard.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "vanguard.fullname" . }}
spec:
  replicas: {{ .Values.deployment.replicas}}
  selector:
    matchLabels:
      app: {{ template "vanguard.fullname" . }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.deployment.annotations.prometheus.port | quote }}
        prometheus.io/path: "/metrics"
      labels:
        app: {{ template "vanguard.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "vanguard.serviceAccount.name" . }}
      containers:
      - name: {{ template "vanguard.name" . }}
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 15
          failureThreshold: 2
        ports:
        - containerPort: 53
          name: dns-port
          protocol: UDP
        - containerPort: 9000
          name: cmd-port
          protocol: TCP
        volumeMounts:
        - name: vanguard-cfg
          mountPath: /etc/vanguard
        resources:
{{ toYaml .Values.deployment.resources | indent 10 }}
      volumes:
      - name: vanguard-cfg
        configMap:
          name: {{ template "vanguard.fullname" . }}
