apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "vanguard.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "vanguard.fullname" . }}
spec:
  selector:
    app: {{ template "vanguard.fullname" . }}
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 53 
      protocol: {{ .Values.service.protocol }} 

