apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-emoji
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-emoji-svc
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-emoji-svc
    spec:
      containers:
      - env:
        - name: GRPC_PORT
          value: "8080"
        image: buoyantio/emojivoto-emoji-svc:v8
        name: emoji-svc
        ports:
        - containerPort: 8080
          name: grpc
        resources:
          requests:
            cpu: 100m
      serviceAccountName: {{ .Release.Name }}-emoji
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-voting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-voting-svc
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-voting-svc
    spec:
      containers:
      - env:
        - name: GRPC_PORT
          value: "8080"
        image: buoyantio/emojivoto-voting-svc:v8
        name: voting-svc
        ports:
        - containerPort: 8080
          name: grpc
        resources:
          requests:
            cpu: 100m
      serviceAccountName: {{ .Release.Name }}-voting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web-svc
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web-svc
    spec:
      containers:
      - env:
        - name: WEB_PORT
          value: "8080"
        - name: EMOJISVC_HOST
          value: {{ .Release.Name }}-emoji-svc:8080
        - name: VOTINGSVC_HOST
          value: {{ .Release.Name }}-voting-svc:8080
        - name: INDEX_BUNDLE
          value: dist/index_bundle.js
        image: buoyantio/emojivoto-web:v8
        name: web-svc
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
      serviceAccountName: {{ .Release.Name }}-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vote-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-vote-bot
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-vote-bot
    spec:
      containers:
      - command:
        - emojivoto-vote-bot
        env:
        - name: WEB_HOST
          value: {{ .Release.Name }}-web-svc:80
        image: buoyantio/emojivoto-web:v8
        name: vote-bot
        resources:
          requests:
            cpu: 10m
