apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-emoji-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-emoji-svc
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-voting-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-voting-svc
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-web-svc
  ports:
  - name: http
    port: 80
    targetPort: 8080
