{{- $persistence := .Values.persistence -}}
{{- $jobservice := .Values.persistence.persistentVolumeClaim.jobservice -}}
{{- if and .Values.persistence.enabled (not $jobservice.existingClaim) }}
{{- if eq .Values.jobservice.jobLogger "file" }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "harbor.jobservice" . }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: jobservice
spec:
  accessModes: 
    - {{ $jobservice.accessMode }}
  resources:
    requests:
      storage: {{ $jobservice.size }}
  {{- if $persistence.storageClass }}
    {{- if eq "-" $persistence.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $persistence.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}